# Map of Citizenship of characters
This short notebook has the aim of creating the map of citizenship.

In [1]:
# Import libraries
import plotly.graph_objects as go
import pandas as pd
import numpy as np
%matplotlib inline
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import math
import re
import string
import pickle

First we need to know the correspondance between citizenship and country, we load a file that aims to do this translation

In [2]:
demonyms = pd.read_csv('demonyms.csv',names=["Citizenship","Country"])
#Rename Russia
demonyms.loc[demonyms['Citizenship']=="Soviet", 'Country']= 'Russian Federation'
demonyms.loc[demonyms['Citizenship']=="Russian", 'Country']= 'Russian Federation'

In order to plot the number of characters on the map, we need to know the ISO code of each country

In [3]:
iso = pd.read_csv('https://github.com/Dinuks/country-nationality-list/raw/master/countries.csv')
iso = iso[["alpha_3_code", "nationality", "en_short_name"]]
iso.columns = ["iso3", "Citizenship", "Country"]
#we merge the demonyms dataframe
iso = iso.merge(demonyms, how="outer", on="Country")
#we saw that united kingdom was missing on the map, so we renamed the country and citizenship of ISO GBR
iso.loc[iso['iso3']=='GBR','Country']='United Kingdom'
iso.loc[iso['iso3']=='GBR','Citizenship_x']='British'
iso.Citizenship_y.fillna(iso.Citizenship_x, inplace=True)
iso =iso.dropna()
iso = iso[["iso3", "Citizenship_y"]]
iso.columns = ["iso3", "Citizenship"]
iso

    iso3      Citizenship
0    AFG           Afghan
1    ALA     Åland Island
2    ALB         Albanian
3    DZA         Algerian
4    ASM  American Samoan
..   ...              ...
356  ESH        Sahrawian
357  YEM           Yemeni
358  YEM         Yemenite
359  ZMB          Zambian
360  ZWE       Zimbabwean

[361 rows x 2 columns]

Now we have a clean correspondance between citizenship and ISO country code. We can now load the charcters and count how much character are in each location. If a character has two citizenship, we count a character for both country

In [4]:
#load dataframe
marvel_pers = pd.read_pickle("marvel_pers_final_2")
#split the citizenship if more than one
marvel_pers['Citizenship'] = marvel_pers['Citizenship'].str.split(',')
marvel_pers = marvel_pers.explode("Citizenship")
marvel_pers['Citizenship'] = marvel_pers['Citizenship'].str.replace(' ','')
#delete the unknown citizenship
marvel_pers.loc[marvel_pers['Citizenship']=="", 'Citizenship'] = 'Unknown'
#merge with our ISO
marvel_pers = marvel_pers.merge(iso, on="Citizenship")
#Group by country
count_map_marvel = marvel_pers.groupby('iso3').count()
count_map_marvel = count_map_marvel['URL']
count_map_marvel = count_map_marvel.to_frame()
count_map_marvel['locations'] = count_map_marvel.index
count_map_marvel.columns = ['z', "locations"]
count_map_marvel.head(5)

       z locations
iso3
AFG    1       AFG
ARG    4       ARG
ARM    1       ARM
AUS   39       AUS
AUT   16       AUT

Let's do the same for DC Comics

In [5]:
#load dataframe
dc_pers = pd.read_pickle("dc_pers_final_2")
#split the citizenship if more than one
dc_pers['Citizenship'] = dc_pers['Citizenship'].str.split(',')
dc_pers = dc_pers.explode("Citizenship")
dc_pers['Citizenship'] = dc_pers['Citizenship'].str.replace(' ','')
#delete the unknown citizenship
dc_pers.loc[dc_pers['Citizenship']=="", 'Citizenship'] = 'Unknown'
#merge with our ISO
dc_pers = dc_pers.merge(iso, on="Citizenship")
#Group by country
count_map_dc = dc_pers.groupby('iso3').count()
count_map_dc = count_map_dc['URL']
count_map_dc = count_map_dc.to_frame()
count_map_dc['locations'] = count_map_dc.index
count_map_dc.columns = ['z', "locations"]
count_map_dc.head(5)

       z locations
iso3
ARG   11       ARG
ARM    1       ARM
AUS   23       AUS
AUT   13       AUT
BOL    1       BOL

**NOW LET'S PLOT IT!**

In [6]:
#Choose the color for the corresponding number of people
vals = [0, 10, 100, 250, 1000, 12000]
colors = ['#ffffcc', '#C2F79E', '#78DE7B', '#31a354', '#003C20']

In [7]:
def make_choropleth1(i, val_range, visi):
    
    color = colors[i]
#####DC#########
    if visi:
        if i != 4:
            return dict(
                type='choropleth',
                locationmode='ISO-3',
                locations=[],
                z=[],
                colorscale=[[0, color], [1, color]],
                zmin=val_range[0],
                hovertext=[],
                hoverinfo="text",
                visible = False,
                zmax=val_range[1],
                colorbar=dict(
                    x=0.99,
                    y=i/float(N) + 0.2,
                    len=1/float(N)- 0.02,
                    tick0=val_range[0],
                    dtick=val_range[1]-val_range[0],
                )
             )
        else:
            return dict(
            type='choropleth',
            locationmode='ISO-3',
            locations=[],
            z=[],
            colorscale=[[0, color], [1, color]],
            zmin=val_range[0],
            hovertext=[],
            hoverinfo="text",
            visible = False,
            zmax=val_range[1],
            colorbar=dict(
                x=0.99,
                y=i/float(N) + 0.2,
                len=1/float(N) + 0.04,
                tick0=val_range[0],
                dtick=val_range[1]-val_range[0],
                title = 'Number of Characters'
            )
            )
        
############Marvel#########
    else:
        if i != 4:
            return dict(
                type='choropleth',
                locationmode='ISO-3',
                locations=[],
                z=[],
                colorscale=[[0, color], [1, color]],
                zmin=val_range[0],
                hovertext=[],
                hoverinfo="text",
                visible = True,
                zmax=val_range[1],
                colorbar=dict(
                    x=0.99,
                    y=i/float(N) + 0.2,
                    len=1/float(N)- 0.02,
                    tick0=val_range[0],
                    dtick=val_range[1]-val_range[0],
                )
             )
        else:
            return dict(
            type='choropleth',
            locationmode='ISO-3',
            locations=[],
            z=[],
            colorscale=[[0, color], [1, color]],
            zmin=val_range[0],
            hovertext=[],
            hoverinfo="text",
            visible = True,
            zmax=val_range[1],
            colorbar=dict(
                x=0.99,
                y=i/float(N) + 0.2,
                len=1/float(N) + 0.04,
                tick0=val_range[0],
                dtick=val_range[1]-val_range[0],
                title = 'Number of Characters'
            )
            )

In [8]:
############# Marvel layout ################
layout_marvel= go.Layout(
    title = go.layout.Title(
        text = 'Number of Characters in Marvel',
        font= {'family':'Komika Hand', 
               'color':'#7f7f7f', 
               'size':20}, 
        x=0, 
        xanchor='left', 
        y=0.95, 
        yanchor='top'
    ),
    geo = go.layout.Geo(
        showframe = False,
        showcoastlines = False,
        showocean= True, 
        oceancolor= "rgb(99,00,00)",
        projection = go.layout.geo.Projection(
            type = 'equirectangular' 
        )
    ),
    font = dict(family='Komika Hand, courant', size=12, color='#7f7f7f'),
)
#############Marvel geo ################
geo_marvel = go.layout.Geo(
        showframe = False,
        showcoastlines = False,
        showocean= True, 
        oceancolor= "rgb(99,00,00)",
        projection = go.layout.geo.Projection(
            type = 'equirectangular' 
        )
    )
############# DC geo ################
geo_dc = go.layout.Geo(
        showframe = False,
        showcoastlines = False,
        showocean= True, 
        oceancolor= "rgb(15,76,129)",
        projection = go.layout.geo.Projection(
            type = 'equirectangular' 
        )
    )

In [9]:
import chart_studio
chart_studio.tools.set_credentials_file(username='Ahko26', api_key='VBmVVv93RzXI5FVJdRj8')

In [10]:
trace = count_map_marvel
N = len(vals)
data = []
for i in range(N-1):
    val_range = [vals[i], vals[i+1]]
    visi=0
    trace_new = make_choropleth1(i, val_range, visi)
    
    for loc, z in zip(trace['locations'], trace['z']):
        if val_range[0] <= z < val_range[1]:
            trace_new['locations'].append(loc)
            trace_new['z'].append(z)
            trace_new['hovertext'].append(str(loc)+ '<br />Nb of Characters: '+ str(z))
       
    data.append(trace_new)
    


########### DC#############
trace = count_map_dc
N = len(vals)
for i in range(N-1):
    val_range = [vals[i], vals[i+1]]
    visi = 1
    trace_new = make_choropleth1(i, val_range, visi)
    
    for loc, z in zip(trace['locations'], trace['z']):
        if val_range[0] <= z < val_range[1]:
            trace_new['locations'].append(loc)
            trace_new['z'].append(z)   
            trace_new['hovertext'].append(str(loc)+ '<br />Nb of Characters: '+ str(z))
    data.append(trace_new)
    
fig = go.Figure(
    data=data,
    layout=layout_marvel,
    
)

visible_marvel= [True]*5 + [False]*5
visible_dc = [False]*5 + [True]*5 
fig['layout']['xaxis']['fixedrange'] = False 
fig['layout']['yaxis']['fixedrange'] = False 
fig.update_layout(
    updatemenus=[
        #category button
        go.layout.Updatemenu(
            active=0,
            pad={"r": 10, "t": 10},
            x=-0.22,
            y=1.1,
            xanchor='left',
            yanchor='top',
            buttons=list([
                dict(label="Marvel",
                     method="update",
                     args=[{"visible": visible_marvel},
                           {"title":'Number of Characters in Marvel',
                               "geo": geo_marvel}]),
                dict(label="DC",
                     method="update",
                     args=[{"visible": visible_dc},
                          {"title":'Number of Characters in DC',
                           "geo": geo_dc}])
            ]),
        )
    ])
py.iplot(fig, filename='testmap.html', auto_open=False)

Let's save this beautiful map on plot.ly, and make it useable on our website

In [11]:
import chart_studio.tools as tls
tls.get_embed('https://plot.ly/~Ahko26/1/')

'<iframe id="igraph" scrolling="no" style="border:none;" seamless="seamless" src="https://plot.ly/~Ahko26/1.embed" height="525" width="100%"></iframe>'